; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; Force une vitesse de televersement plus lente et plus fiable pour eviter les erreurs de communication
upload_speed = 115200

; Script a executer apres une compilation reussie pour copier le firmware
extra_scripts = copy_firmware.py

build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D PIO_ENV_NAME="\"${PIOENV}\""
lib_deps = 
	fastled/FastLED
	tzapu/WiFiManager
	bblanchon/ArduinoJson
